[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[terminal.shell]
args = ["-l"]
program = "fish"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5
